direction: down

vars: {
  d2-config: {
#     layout-engine: elk
    theme-id: 8
  }
}

# client
# webapp
# oauth/saml
# rego
# job db
# job spawner/tracker

client: {
  label: Client
  shape: person
  style.multiple: true
}
idp: {
  label: Identity Provider (oidc/saml)
  shape: cloud
}
portal: {
  label: support-portal
  label.near: top-center
  opa: {
    label: openpolicyagent
  }
  webapp: {
    label: webapp
  }
  runner: {
    label: runner
  }
  opa -> webapp
  webapp -> runner
}
db: {
  label: database
  shape: cylinder
}
jobs: {
  label: jobs
  style.multiple: true
}
Client -> portal.webapp
Client -> idp
idp -> portal.opa
portal.webapp -> db
portal.runner -> jobs
portal.runner -> db
